ecommerce_app/account/urls.py
from django.urls import path
from account.views import update_account_view, account_home_view, change_password_view, order_list_view,
order_detail_view, shopping_cart_list_view, shopping_cart_detail_view

app_name = 'account'

urlpatterns = [
    path('', account_home_view, name='home'),
    path('update/', update_account_view, name='update'),
    path('change-password/', change_password_view, name='change-password'),
    path('order/', order_list_view, name='order-list'),
    path('order/<int:pk>/', order_detail_view, name='order-detail'),
    path('shopping-cart/', shopping_cart_list_view, name='shopping-cart-list'),
    path('shopping-cart/<int:pk>/', shopping_cart_detail_view, name='shopping-cart-detail'),
]

ecommerce_app/ecommerce_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from ecommerce_app.views import home_view, login_view, logout_view

app_name = 'ecommerce'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home')
    path('api/v1/', include('restapi.urls'), namespace='restapi'),
    path('account/', include('account.urls', namespace='account')),
    path('product/', include('product.urls', namespace='product')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

ecommerce_app/product/urls.py
from django.urls import path
from product.views import product_create_view, product_update_view,
product_detail_view, product_delete_view, product_category_list_view,
product_category_detail_view

app_name = 'product'

urlpatterns = [
    path('products/', product_create_view, name='create'),
    path('products/<int:pk>/', product_detail_view, name='detail'),
    # path('products/<int:pk>/', product_delete_view, name='delete'),
    path('products/<ink:pk>/', product_update_view, name='update'),
    path('products/<ink:pk>/category/<str:category>/', product_category_list_view, name='category-list'),
    path('products/<ink:pk>/category/<str:category>/<int:pk>/', product_category_detail_view, name='category-detail'),
]

ecommerce_app/product/models.py
from django.db import models
from django.shortcuts import reverse


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=50, default='')
    price = models.IntegerField(default=000)
    category = models.TextField(default='', max_length='60')
    image = models.ImageField(upload_to='product_image', default='None')
    created = models.DateTimeField(auto_add_now=True)
    updated = models.DateTimeField(auto_now=True)
    quantity = models.PositiveIntegerField(null=True)
    total_price = models.FloatField(blank=True, null=True)
    vat = modes.FloatField(blank=True)

    def __str__(self):
        return f"Product for the price of {self.price}"

    def get_absolute_url(self):
        return reverse('product:detail', kwargs={'pk': self.pk})

    def get_vat(self):
        return self.vat

class ProductUploadImag(models.Model):
    file_name = models.CharField(max_length=120, null=True)
    product_file = models.FileField(upload_to='product_image', null=True)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.file_name)

ecommerce_app/product/forms.py
from django import forms
from product.models import ProductUploadImag


class ProductSearchForm(forms.Form):
    name = forms.TextField(widget=forms.TextInput(attrs={'type': 'text'}))
    category = forms.TextField(widget=forms.TextInput(attrs={'type': 'text'}))

class ProductCreationForm(forms.ModelForm):
    class Meta:
        model = ProductUploadImag
        fields = '__all__'

class ProductUpdateForm(forms.ModelForm):
    pass

ecommerce_app/product/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from product.models import ProductUploadImag
from django.http import HttpResponse, JsonResponse
from django.template.loader import get_template
from django.views import generic
from django.utils import timezone

# Create your views here.

def product_create_view(request):
    pass

def product_update_view(request, pk):
    pass

def product_detail_view(request, pk):
    pass

def product_delete_view(request, pk):
    pass

def product_category_list_view(request, pk, category):
    pass

def product_category_detail_view(request, pk, category, pk):
    pass

@login_required
def product_upload_view(request):
    if request.method == 'POST':
        product_file_name = request.FILES.get('file').name
        product_file = request.FILES.get('file')
        obj, created = ProductUploadImag.objects.get_or_create(file_name=product_file_name)

        if created:
            obj.product_file = product_file
            obj.save()
            with open(obj.product_file.path, 'r') as f:
                reader = uploadService.read(f)
                return HttpResponse(data=reader, content_type='image/jpeg')
        else:
            return JsonResponse({'ex': 'Error'})
    else:
        return HttpResponse()

@login_required
def create_product_data(request):
    form = ProductCreateForm(request.POST or None)
    if request.is_fetch():
        image = request.POST.get('image')
        img = get_product_image(image)
        account = Accout.objects.get(user=request.user)

        if form.is_valid():
            instance = form.save(commit=False)
            instance.image = image
            instance.account = account
            instance.save()
        return JsonResponse({'msg': 'send'})
    return JsonResponse({})

@login_required
def render_data_view(request, pk):
    template_path = 'productCreateForm/data.html'
    obj = get_object_404(ProductUploadImag, pk=pk)
    context = {'obj': obj}
    response = HttpResponse(content_type='image/jpeg')
    response['Content-Disposition'] = 'filename="image_file.jpeg"'
    template = get_template(template_path)
    html = template.render(context)

class IndexView(generic.ListView):
    template_name = 'products/index.html'
    context_object_name = 'product_data_list'

    def get_queryset(self):
        return  Product.objects.filter(
            created__lte=timezone.now()
        )
        order_by('-created')[:5]


class DetailView(generic.DetailView):
    def get_queryset(self):
        return Product.objects.filter(created=timezone.now())

ecommerce_app/product/templates/product/product_category_detail.html
{% load static %}
{% load crispy_form_tags %}


{% block content %}


<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title></title>
</head>
<body>

</body>
</html>

{% block content %}

ecommerce_app/product/templates/product/product_category_list.view.html
{% load static %}
{% load crispy_form_tags %}


{% block content %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title></title>
</head>
<body>

</body>
</html>

{% endblock %}

ecommerce_app/product/templates/product/product_create.html
{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms %}

{% block content %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Product Create View</title>
  <link rel="stylesheet" type="text/css" href="{% static 'styles/main.css' %}">
</head>
<body>

  {% if user.is_authenticated %}
    <div class="header-login">
      <div class="header-logo">
        App Logo
      </div>
      <div class="right-side-button">
          <a href="{% url 'ecommerce:logout' %}">Logout</a>
      </div>
    </div>
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% form %}
      <button type="submit">Create Product</button>
    </form>

    <div>
      <p><a href="{% url 'account:home' %}">Return to home</a></p>
    </div>
  {% else %}
  <div class="header-logout">
    <div class="App logo">
      App Logo
    </div>
    <div class="right-side-button">
      <a href="{% url 'ecommerce:login' %}">Login</a>
    </div>
  </div>
  {% endif %}
</body>
</html>

{% end block %}

ecommerce_app/product/templates/product/product_detail.html
{% load static %}
{% load crispy_form_tags %}
{% load crispy_forms %}

{% block content %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Product Detail - {{ product.name }} - {{ product.category }}</title>
  <link rel="stylesheet" type="text/css" href="{% static 'styles/main.css' %}">
</head>
<body>
  <div class="product-details">
    <h1>{{ product.name }}</h1>
    <p>{{ product.category }}</p>
    <p>{{ product.price }}</p>
  </div>
  <div class="product-list">
    {% for product in product_list %}
      <a href="{% url 'product:detail' product.id %}">
        <p class="product-name">
          {{ product.name }}
        </p>
        <p class="product-description">
          {{ product.description }}
        </p>
        <p class="product-manufacturer">
          {{ product.manufacturer }}
        </p>
      </a>
    {% endfor %}
  </div>
  <a href="{% url 'ecommerce:home' %}">Return to Home</a>
</body>
</html>

{% endblock %}}

ecommerce_app/product/templates/product/product_update.html
{% load static %}
{% load crispy_form tags %}
{% load crispy_forms %}

{% block content %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Product Update - {{ product.name }} - {{ product.category }}</title>
  <link rel="stylesheet" type="text/css" href="{% static 'styles/main.css' %}">
</head>
<body>
  {% if user.is_authenticated %}
    <h1>{{ product.name }}</h1>-<span>{{ product.category }}</span>
    <form action="" method="PUT" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
    </form>
    <div class="upload-multiple">
      <button type="button" class="btn">
        <span class="upload button">Upload Photos</span>
      </button>
      <div>
        <input id="filesupload" type="file" name="file" multiple data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}' />
      </div>
    </div>
    <div class="drag-drop-contained">
      <h3>Drop photos here to upload</h3>
    </div>
  {% else %}
    <div class="redirect-home">
      <a href="{% url 'ecommerce:home' %}">Return Home</a>
    </div>
  {% endif %}

</body>
</html>

{% endblock %}